import Foundation

enum ItalianContent {
    static let vocabulary: [VocabularyItem] = [
        VocabularyItem(id: 1, category: .essential, section: "Wichtige Phrasen", italian: "Mi chiamo Tobias, sono tedesco e vengo da Berlino, in Germania.", pronunciation: "mi kjamo Tobias, sono tedesko e wengo da Berlino, in dschermania", german: "Ich bin Tobias, ich bin Deutscher und komme aus Berlin in Deutschland."),
        VocabularyItem(id: 2, category: .essential, section: "Wichtige Phrasen", italian: "Scusi!", pronunciation: "skusi", german: "Entschuldigen Sie! / Entschuldigung!"),
        VocabularyItem(id: 3, category: .essential, section: "Wichtige Phrasen", italian: "Grazie.", pronunciation: "gratsje", german: "Danke."),
        VocabularyItem(id: 4, category: .essential, section: "Wichtige Phrasen", italian: "Anch’io.", pronunciation: "ankio", german: "Ich auch."),
        VocabularyItem(id: 5, category: .essential, section: "Wichtige Phrasen", italian: "Mi può aiutare?", pronunciation: "mi puo aiutare", german: "Können Sie mir helfen?"),
        VocabularyItem(id: 6, category: .essential, section: "Wichtige Phrasen", italian: "Non parlo italiano.", pronunciation: "non parlo italjano", german: "Ich spreche kein Italienisch."),
        VocabularyItem(id: 7, category: .essential, section: "Wichtige Phrasen", italian: "Parla inglese?", pronunciation: "parla inglese", german: "Sprechen Sie Englisch?"),
        VocabularyItem(id: 8, category: .essential, section: "Wichtige Phrasen", italian: "Parla tedesco?", pronunciation: "parla tedesko", german: "Sprechen Sie Deutsch?"),
        VocabularyItem(id: 9, category: .essential, section: "Wichtige Phrasen", italian: "Non capisco.", pronunciation: "non kapisko", german: "Ich verstehe nicht."),
        VocabularyItem(id: 10, category: .essential, section: "Wichtige Phrasen", italian: "Non ho capito.", pronunciation: "non o kapito", german: "Ich habe es nicht verstanden."),
        VocabularyItem(id: 11, category: .essential, section: "Wichtige Phrasen", italian: "Dov’è …?", pronunciation: "dowe", german: "Wo ist …?"),
        VocabularyItem(id: 12, category: .essential, section: "Wichtige Phrasen", italian: "Dov’è il bagno?", pronunciation: "dowe il banjo", german: "Wo ist die Toilette?"),
        VocabularyItem(id: 13, category: .essential, section: "Wichtige Phrasen", italian: "Quanto costa?", pronunciation: "kwanto kosta", german: "Wie viel kostet es?"),
        VocabularyItem(id: 14, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Ciao!", pronunciation: "tschau", german: "Hallo! / Tschüss!"),
        VocabularyItem(id: 15, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Buongiorno!", pronunciation: "buon-dschorno", german: "Guten Morgen! / Guten Tag!"),
        VocabularyItem(id: 16, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Buon pomeriggio!", pronunciation: "buon pomeriddscho", german: "Guten Nachmittag!"),
        VocabularyItem(id: 17, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Buonasera!", pronunciation: "buona-sera", german: "Guten Abend!"),
        VocabularyItem(id: 18, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Buonanotte!", pronunciation: "buona-notte", german: "Gute Nacht!"),
        VocabularyItem(id: 19, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "A presto!", pronunciation: "a presto", german: "Bis bald!"),
        VocabularyItem(id: 20, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "È tutto per oggi.", pronunciation: "e tutto per oddschi", german: "Das ist alles für heute."),
        VocabularyItem(id: 21, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Come ti chiami?", pronunciation: "kome ti kjami", german: "Wie heißt du?"),
        VocabularyItem(id: 22, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Come si chiama?", pronunciation: "kome si kjama", german: "Wie heißen Sie?"),
        VocabularyItem(id: 23, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Mi chiamo …", pronunciation: "mi kjamo", german: "Ich heiße …"),
        VocabularyItem(id: 24, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Mi chiamo Tobias.", pronunciation: "mi kjamo Tobias", german: "Ich heiße Tobias."),
        VocabularyItem(id: 25, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Sono …", pronunciation: "sono", german: "Ich bin …"),
        VocabularyItem(id: 26, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Piacere!", pronunciation: "pjatschere", german: "Freut mich!"),
        VocabularyItem(id: 27, category: .greetings, section: "Begrüßung und Verabschiedung", italian: "Piacere mio!", pronunciation: "pjatschere mio", german: "Ganz meinerseits!"),
        VocabularyItem(id: 28, category: .wellbeing, section: "Wie geht es dir?", italian: "Come stai?", pronunciation: "kome stai", german: "Wie geht es dir? (informell)"),
        VocabularyItem(id: 29, category: .wellbeing, section: "Wie geht es dir?", italian: "E tu?", pronunciation: "e tu", german: "Und du? (informell)"),
        VocabularyItem(id: 30, category: .wellbeing, section: "Wie geht es dir?", italian: "Come sta?", pronunciation: "kome sta", german: "Wie geht es Ihnen? (höflich)"),
        VocabularyItem(id: 31, category: .wellbeing, section: "Wie geht es dir?", italian: "E Lei?", pronunciation: "e läi", german: "Und Sie? (höflich)"),
        VocabularyItem(id: 32, category: .wellbeing, section: "Wie geht es dir?", italian: "Come va?", pronunciation: "kome wa", german: "Wie läuft es?"),
        VocabularyItem(id: 33, category: .wellbeing, section: "Wie geht es dir?", italian: "Bene, grazie. E tu?", pronunciation: "bene, gratsje. e tu", german: "Gut, danke. Und dir?"),
        VocabularyItem(id: 34, category: .wellbeing, section: "Wie geht es dir?", italian: "Molto bene.", pronunciation: "molto bene", german: "Sehr gut."),
        VocabularyItem(id: 35, category: .wellbeing, section: "Wie geht es dir?", italian: "Benissimo!", pronunciation: "benissimo", german: "Ausgezeichnet! / Sehr, sehr gut!"),
        VocabularyItem(id: 36, category: .wellbeing, section: "Wie geht es dir?", italian: "Sto bene.", pronunciation: "sto bene", german: "Mir geht es gut."),
        VocabularyItem(id: 37, category: .wellbeing, section: "Wie geht es dir?", italian: "Sono un po’ stanco.", pronunciation: "sono un po stanko", german: "Ich bin ein bisschen müde. (männlich)"),
        VocabularyItem(id: 38, category: .wellbeing, section: "Wie geht es dir?", italian: "un po’", pronunciation: "un po", german: "ein bisschen"),
        VocabularyItem(id: 39, category: .wellbeing, section: "Wie geht es dir?", italian: "stanco / stanca", pronunciation: "stanko / stanka", german: "müde · männlich / weiblich"),
        VocabularyItem(id: 40, category: .wellbeing, section: "Wie geht es dir?", italian: "Ho troppo lavoro.", pronunciation: "o troppo laworo", german: "Ich habe zu viel Arbeit."),
        VocabularyItem(id: 41, category: .wellbeing, section: "Wie geht es dir?", italian: "troppo", pronunciation: "troppo", german: "zu viel"),
        VocabularyItem(id: 42, category: .wellbeing, section: "Wie geht es dir?", italian: "il lavoro", pronunciation: "il laworo", german: "die Arbeit"),
        VocabularyItem(id: 43, category: .wellbeing, section: "Wie geht es dir?", italian: "Male.", pronunciation: "male", german: "Schlecht."),
        VocabularyItem(id: 44, category: .wellbeing, section: "Wie geht es dir?", italian: "Molto male.", pronunciation: "molto male", german: "Sehr schlecht."),
        VocabularyItem(id: 45, category: .wellbeing, section: "Wie geht es dir?", italian: "Malissimo!", pronunciation: "malissimo", german: "Furchtbar!"),
        VocabularyItem(id: 46, category: .wellbeing, section: "Wie geht es dir?", italian: "Così così.", pronunciation: "kosi kosi", german: "So lala."),
        VocabularyItem(id: 47, category: .wellbeing, section: "Wie geht es dir?", italian: "Non c’è male.", pronunciation: "non tsche male", german: "Nicht schlecht."),
        VocabularyItem(id: 48, category: .wellbeing, section: "Wie geht es dir?", italian: "Oggi sto male.", pronunciation: "oddschi sto male", german: "Heute geht es mir schlecht."),
        VocabularyItem(id: 49, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "io", pronunciation: "io", german: "ich"),
        VocabularyItem(id: 50, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "tu", pronunciation: "tu", german: "du"),
        VocabularyItem(id: 51, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "lui", pronunciation: "lui", german: "er"),
        VocabularyItem(id: 52, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "lei", pronunciation: "läi", german: "sie"),
        VocabularyItem(id: 53, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Lei", pronunciation: "läi", german: "Sie (höflich)"),
        VocabularyItem(id: 54, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "noi", pronunciation: "noi", german: "wir"),
        VocabularyItem(id: 55, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "voi", pronunciation: "woi", german: "ihr / Sie (Mehrzahl)"),
        VocabularyItem(id: 56, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "loro", pronunciation: "loro", german: "sie (Mehrzahl)"),
        VocabularyItem(id: 57, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "essere", pronunciation: "essere", german: "sein"),
        VocabularyItem(id: 58, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "abitare", pronunciation: "abitare", german: "wohnen"),
        VocabularyItem(id: 59, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "io abito", pronunciation: "io abito", german: "ich wohne"),
        VocabularyItem(id: 60, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "tu abiti", pronunciation: "tu abiti", german: "du wohnst"),
        VocabularyItem(id: 61, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "lui / lei / Lei abita", pronunciation: "lui / läi / läi abita", german: "er / sie wohnt · Sie wohnen"),
        VocabularyItem(id: 62, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "noi abitiamo", pronunciation: "noi abitjamo", german: "wir wohnen"),
        VocabularyItem(id: 63, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "voi abitate", pronunciation: "woi abitate", german: "ihr wohnt · Sie wohnen (Mehrzahl)"),
        VocabularyItem(id: 64, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "loro abitano", pronunciation: "loro abitano", german: "sie wohnen"),
        VocabularyItem(id: 65, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Tom e Mark abitano in Germania.", pronunciation: "Tom e Mark abitano in dschermania", german: "Tom und Mark wohnen in Deutschland."),
        VocabularyItem(id: 66, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Io abito in Italia. / Abito in Italia?", pronunciation: "io abito in italja / abito in italja", german: "Ich wohne in Italien. / Wohne ich in Italien?"),
        VocabularyItem(id: 67, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Tu abiti in Italia. / Abiti in Italia?", pronunciation: "tu abiti in italja / abiti in italja", german: "Du wohnst in Italien. / Wohnst du in Italien?"),
        VocabularyItem(id: 68, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Lui abita in Italia. / Abita in Italia?", pronunciation: "lui abita in italja / abita in italja", german: "Er wohnt in Italien. / Wohnt er in Italien?"),
        VocabularyItem(id: 69, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Lei abita in Italia. / Abita in Italia?", pronunciation: "läi abita in italja / abita in italja", german: "Sie wohnt in Italien. / Wohnt sie in Italien? · höflich auch: Sie wohnen / Wohnen Sie in Italien?"),
        VocabularyItem(id: 70, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Noi abitiamo in Italia. / Abitiamo in Italia?", pronunciation: "noi abitjamo in italja / abitjamo in italja", german: "Wir wohnen in Italien. / Wohnen wir in Italien?"),
        VocabularyItem(id: 71, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Voi abitate in Italia. / Abitate in Italia?", pronunciation: "woi abitate in italja / abitate in italja", german: "Ihr wohnt in Italien. / Wohnt ihr in Italien?"),
        VocabularyItem(id: 72, category: .grammar, section: "Grammatik · Personalpronomen und Verben", italian: "Loro abitano in Italia. / Abitano in Italia?", pronunciation: "loro abitano in italja / abitano in italja", german: "Sie wohnen in Italien. / Wohnen sie in Italien?"),
        VocabularyItem(id: 73, category: .alphabet, section: "Das italienische Alphabet", italian: "A – B – C – D – E", pronunciation: "a – bi – tschi – di – e", german: "Buchstabennamen A bis E"),
        VocabularyItem(id: 74, category: .alphabet, section: "Das italienische Alphabet", italian: "F – G – H – I", pronunciation: "effe – dschi – akka – i", german: "Buchstabennamen F bis I"),
        VocabularyItem(id: 75, category: .alphabet, section: "Das italienische Alphabet", italian: "L – M – N – O", pronunciation: "elle – emme – enne – o", german: "Buchstabennamen L bis O"),
        VocabularyItem(id: 76, category: .alphabet, section: "Das italienische Alphabet", italian: "P – Q – R – S – T", pronunciation: "pi – ku – erre – esse – ti", german: "Buchstabennamen P bis T"),
        VocabularyItem(id: 77, category: .alphabet, section: "Das italienische Alphabet", italian: "U – V – Z", pronunciation: "u – wi / wu – dzeta", german: "Buchstabennamen U, V und Z"),
        VocabularyItem(id: 78, category: .alphabet, section: "Das italienische Alphabet", italian: "J – K – W – X – Y", pronunciation: "i lunga – kappa – doppia wu – iks – ipsilon", german: "Zusatzbuchstaben, vor allem in Fremdwörtern und Namen"),
        VocabularyItem(id: 79, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Ho una prenotazione a nome di …", pronunciation: "o una prenotatsjone a nome di", german: "Ich habe eine Reservierung auf den Namen …"),
        VocabularyItem(id: 80, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Vorrei prenotare un tavolo per due persone.", pronunciation: "vorrei prenotare un tavolo per due persone", german: "Ich möchte einen Tisch für zwei Personen reservieren."),
        VocabularyItem(id: 81, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Vorrei prenotare un tavolo per due persone alle otto.", pronunciation: "vorrei prenotare un tavolo per due persone alle otto", german: "Ich möchte einen Tisch für zwei Personen um 20 Uhr reservieren."),
        VocabularyItem(id: 82, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Avete un tavolo libero per due?", pronunciation: "avete un tavolo libero per due", german: "Haben Sie einen freien Tisch für zwei?"),
        VocabularyItem(id: 83, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Siamo in due.", pronunciation: "sjamo in due", german: "Wir sind zu zweit."),
        VocabularyItem(id: 84, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Vorrei un tavolo per quattro.", pronunciation: "vorrei un tavolo per kwattro", german: "Ich möchte einen Tisch für vier Personen."),
        VocabularyItem(id: 85, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Possiamo sederci fuori?", pronunciation: "possjamo sedertschi fwori", german: "Können wir draußen sitzen?"),
        VocabularyItem(id: 86, category: .restaurant, section: "Restaurant · Tisch und Reservierung", italian: "Possiamo sederci dentro?", pronunciation: "possjamo sedertschi dentro", german: "Können wir drinnen sitzen?"),
        VocabularyItem(id: 87, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Il menù, per favore.", pronunciation: "il menu, per favore", german: "Die Speisekarte, bitte."),
        VocabularyItem(id: 88, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Posso avere il menù, per favore?", pronunciation: "posso avere il menu, per favore", german: "Kann ich bitte die Speisekarte haben?"),
        VocabularyItem(id: 89, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Cosa mi consiglia?", pronunciation: "kosa mi konsilja", german: "Was empfehlen Sie mir?"),
        VocabularyItem(id: 90, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Vorrei ordinare, per favore.", pronunciation: "vorrei ordinare, per favore", german: "Ich möchte gern bestellen."),
        VocabularyItem(id: 91, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Vorrei …", pronunciation: "vorrei", german: "Ich hätte gern … / Ich möchte …"),
        VocabularyItem(id: 92, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Per me …, per favore.", pronunciation: "per me, per favore", german: "Für mich …, bitte."),
        VocabularyItem(id: 93, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Prendo …", pronunciation: "prendo", german: "Ich nehme …"),
        VocabularyItem(id: 94, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Vorrei il ragù, per favore.", pronunciation: "vorrei il ragu, per favore", german: "Ich hätte gern das Ragù, bitte."),
        VocabularyItem(id: 95, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Prendo il tiramisù.", pronunciation: "prendo il tiramisu", german: "Ich nehme das Tiramisù."),
        VocabularyItem(id: 96, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Vorremmo un tiramisù e due caffè espressi.", pronunciation: "vorremmo un tiramisu e due kaffe espressi", german: "Wir hätten gerne ein Tiramisù und zwei Espressi."),
        VocabularyItem(id: 97, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Posso avere …?", pronunciation: "posso avere", german: "Kann ich … haben?"),
        VocabularyItem(id: 98, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "Senza …, per favore.", pronunciation: "sentsa, per favore", german: "Ohne …, bitte."),
        VocabularyItem(id: 99, category: .restaurant, section: "Restaurant · Speisekarte und Bestellen", italian: "È tutto, grazie.", pronunciation: "e tutto, gratsje", german: "Das ist alles, danke."),
        VocabularyItem(id: 100, category: .restaurant, section: "Restaurant · Getränke", italian: "Vorrei un bicchiere d’acqua naturale.", pronunciation: "vorrei un bik-kjere dak-kwa naturale", german: "Ich möchte ein Glas stilles Wasser."),
        VocabularyItem(id: 101, category: .restaurant, section: "Restaurant · Getränke", italian: "Una bottiglia d’acqua naturale, per favore.", pronunciation: "una bottilja dak-kwa naturale, per favore", german: "Eine Flasche stilles Wasser, bitte."),
        VocabularyItem(id: 102, category: .restaurant, section: "Restaurant · Getränke", italian: "Una bottiglia d’acqua frizzante, per favore.", pronunciation: "una bottilja dak-kwa frittsante, per favore", german: "Eine Flasche Sprudelwasser, bitte."),
        VocabularyItem(id: 103, category: .restaurant, section: "Restaurant · Getränke", italian: "Vorrei un bicchiere di vino bianco, per favore.", pronunciation: "vorrei un bik-kjere di vino bjanko, per favore", german: "Ich möchte ein Glas Weißwein, bitte."),
        VocabularyItem(id: 104, category: .restaurant, section: "Restaurant · Getränke", italian: "Vorrei un bicchiere di vino rosso, per favore.", pronunciation: "vorrei un bik-kjere di vino rosso, per favore", german: "Ich möchte ein Glas Rotwein, bitte."),
        VocabularyItem(id: 105, category: .restaurant, section: "Restaurant · Getränke", italian: "Vorrei un bicchiere di vino rosato, per favore.", pronunciation: "vorrei un bik-kjere di vino rosato, per favore", german: "Ich möchte ein Glas Roséwein, bitte."),
        VocabularyItem(id: 106, category: .restaurant, section: "Restaurant · Getränke", italian: "Vorrei una bottiglia di vino, per favore.", pronunciation: "vorrei una bottilja di vino, per favore", german: "Ich möchte eine Flasche Wein, bitte."),
        VocabularyItem(id: 107, category: .restaurant, section: "Restaurant · Getränke", italian: "Un caffè, per favore.", pronunciation: "un kaffe, per favore", german: "Einen Kaffee, bitte."),
        VocabularyItem(id: 108, category: .restaurant, section: "Restaurant · Getränke", italian: "Ancora una bottiglia d’acqua, per favore.", pronunciation: "ankora una bottilja dak-kwa, per favore", german: "Noch eine Flasche Wasser, bitte."),
        VocabularyItem(id: 109, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "Posso avere il conto, per favore?", pronunciation: "posso avere il konto, per favore", german: "Kann ich bitte die Rechnung haben?"),
        VocabularyItem(id: 110, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "Il conto, per favore.", pronunciation: "il konto, per favore", german: "Die Rechnung, bitte."),
        VocabularyItem(id: 111, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "Posso pagare con la carta?", pronunciation: "posso pagare kon la karta", german: "Kann ich mit Karte bezahlen?"),
        VocabularyItem(id: 112, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "Posso pagare la mancia con la carta?", pronunciation: "posso pagare la mantscha kon la karta", german: "Kann ich das Trinkgeld mit Karte bezahlen?"),
        VocabularyItem(id: 113, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "È molto buono.", pronunciation: "e molto buono", german: "Es schmeckt sehr gut."),
        VocabularyItem(id: 114, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "Era delizioso.", pronunciation: "era delizioso", german: "Es war köstlich."),
        VocabularyItem(id: 115, category: .restaurant, section: "Restaurant · Rechnung und Rückmeldung", italian: "È stato molto buono.", pronunciation: "e stato molto buono", german: "Es war sehr gut."),
        VocabularyItem(id: 116, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "ragazzo", pronunciation: "ragattso", german: "Junge / junger Mann"),
        VocabularyItem(id: 117, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "ragazza", pronunciation: "ragattsa", german: "Mädchen / junge Frau"),
        VocabularyItem(id: 118, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "ragazzi", pronunciation: "ragattsi", german: "Jungen / junge Leute · als Anrede: Leute!"),
        VocabularyItem(id: 119, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "ragazze", pronunciation: "ragattse", german: "Mädchen / junge Frauen"),
        VocabularyItem(id: 120, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Oggi", pronunciation: "oddschi", german: "heute"),
        VocabularyItem(id: 121, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Adesso", pronunciation: "adesso", german: "jetzt / nun"),
        VocabularyItem(id: 122, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Ma", pronunciation: "ma", german: "aber"),
        VocabularyItem(id: 123, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Ho …", pronunciation: "o", german: "Ich habe …"),
        VocabularyItem(id: 124, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Voglio", pronunciation: "wolljo", german: "Ich will / ich möchte (direkt; vorrei ist höflicher)."),
        VocabularyItem(id: 125, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Voglio un caffè.", pronunciation: "wolljo un kaffe", german: "Ich möchte einen Kaffee."),
        VocabularyItem(id: 126, category: .everyday, section: "Alltag · Grundwörter und Satzmuster", italian: "Non voglio.", pronunciation: "non wolljo", german: "Ich will nicht."),
        VocabularyItem(id: 127, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Sei", pronunciation: "säi", german: "du bist (2. Person Singular von essere )"),
        VocabularyItem(id: 128, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Di dove sei?", pronunciation: "di dowe säi", german: "Woher kommst du? (informell)"),
        VocabularyItem(id: 129, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Di dov’è?", pronunciation: "di dowe", german: "Woher kommen Sie? (höflich)"),
        VocabularyItem(id: 130, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Sono di Berlino.", pronunciation: "sono di berlino", german: "Ich komme aus Berlin."),
        VocabularyItem(id: 131, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Sono tedesco.", pronunciation: "sono tedesko", german: "Ich bin Deutscher."),
        VocabularyItem(id: 132, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Veniamo da Alessio.", pronunciation: "wenjamo da Alessjo", german: "Wir kommen von Alessio."),
        VocabularyItem(id: 133, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "E tu? Di dove sei?", pronunciation: "e tu, di dowe säi", german: "Und du? Woher kommst du?"),
        VocabularyItem(id: 134, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "E Lei? Di dov’è?", pronunciation: "e läi, di dowe", german: "Und Sie? Woher kommen Sie?"),
        VocabularyItem(id: 135, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "Sono tedesca.", pronunciation: "sono tedeska", german: "Ich bin Deutsche."),
        VocabularyItem(id: 136, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "italiano / italiana", pronunciation: "italjano / italjana", german: "italienisch / Italiener / Italienerin"),
        VocabularyItem(id: 137, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "americano / americana", pronunciation: "amerikano / amerikana", german: "amerikanisch / Amerikaner / Amerikanerin"),
        VocabularyItem(id: 138, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "spagnolo / spagnola", pronunciation: "spanjolo / spanjola", german: "spanisch / Spanier / Spanierin"),
        VocabularyItem(id: 139, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "francese", pronunciation: "frantschese", german: "französisch / Franzose / Französin"),
        VocabularyItem(id: 140, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "scozzese", pronunciation: "skottsese", german: "schottisch / Schotte / Schottin"),
        VocabularyItem(id: 141, category: .origin, section: "Herkunft und Nationalität · CBI 1–03", italian: "irlandese", pronunciation: "irlandese", german: "irisch / Ire / Irin"),
        VocabularyItem(id: 142, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Dove abiti?", pronunciation: "dowe abiti", german: "Wo wohnst du? (informell)"),
        VocabularyItem(id: 143, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Dove abita?", pronunciation: "dowe abita", german: "Wo wohnen Sie? (höflich)"),
        VocabularyItem(id: 144, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito in Germania.", pronunciation: "abito in dschermania", german: "Ich wohne / lebe in Deutschland."),
        VocabularyItem(id: 145, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Berlino, in Germania.", pronunciation: "abito a berlino, in dschermania", german: "Ich wohne in Berlin, in Deutschland."),
        VocabularyItem(id: 146, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Firenze, in Italia.", pronunciation: "abito a firentse, in italja", german: "Ich wohne in Florenz, in Italien."),
        VocabularyItem(id: 147, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Glasgow, in Scozia.", pronunciation: "abito a gläsgou, in skotsja", german: "Ich wohne in Glasgow, in Schottland."),
        VocabularyItem(id: 148, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Londra, in Inghilterra.", pronunciation: "abito a londra, in ingilterra", german: "Ich wohne in London, in England."),
        VocabularyItem(id: 149, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Dublino, in Irlanda.", pronunciation: "abito a dublino, in irlanda", german: "Ich wohne in Dublin, in Irland."),
        VocabularyItem(id: 150, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a New York, negli Stati Uniti.", pronunciation: "abito a nju jork, nellji stati uniti", german: "Ich wohne in New York, in den USA."),
        VocabularyItem(id: 151, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Sydney, in Australia.", pronunciation: "abito a sidni, in australia", german: "Ich wohne in Sydney, in Australien."),
        VocabularyItem(id: 152, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Roma, in Italia. E tu?", pronunciation: "abito a roma, in italja. e tu", german: "Ich wohne in Rom, in Italien. Und du?"),
        VocabularyItem(id: 153, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito in Scozia, a Edimburgo.", pronunciation: "abito in skotsja, a edimburgo", german: "Ich wohne in Schottland, in Edinburgh."),
        VocabularyItem(id: 154, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abiti a Milano?", pronunciation: "abiti a milano", german: "Wohnst du in Mailand?"),
        VocabularyItem(id: 155, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "No, non abito a Milano.", pronunciation: "no, non abito a milano", german: "Nein, ich wohne nicht in Mailand."),
        VocabularyItem(id: 156, category: .origin, section: "Wohnort und Länder · CBI 1–04", italian: "Abito a Trieste.", pronunciation: "abito a trieste", german: "Ich wohne in Triest."),
        VocabularyItem(id: 157, category: .travel, section: "Unterwegs und Parken", italian: "Dov’è il parcheggio?", pronunciation: "dowe il parkeddscho", german: "Wo ist der Parkplatz?"),
        VocabularyItem(id: 158, category: .travel, section: "Unterwegs und Parken", italian: "Dove posso parcheggiare?", pronunciation: "dowe posso parkeddschare", german: "Wo kann ich parken?"),
        VocabularyItem(id: 159, category: .travel, section: "Unterwegs und Parken", italian: "Possiamo parcheggiare qui?", pronunciation: "possjamo parkeddschare kwi", german: "Können wir hier parken?"),
        VocabularyItem(id: 160, category: .travel, section: "Unterwegs und Parken", italian: "C’è un parcheggio qui vicino?", pronunciation: "tsche un parkeddscho kwi witschino", german: "Gibt es hier in der Nähe einen Parkplatz?"),
        VocabularyItem(id: 161, category: .travel, section: "Unterwegs und Parken", italian: "Un biglietto per …, per favore.", pronunciation: "un biljett-o per, per favore", german: "Eine Fahrkarte nach …, bitte."),
        VocabularyItem(id: 162, category: .smallTalk, section: "Small Talk", italian: "Sono in vacanza.", pronunciation: "sono in wakantsa", german: "Ich bin im Urlaub."),
        VocabularyItem(id: 163, category: .smallTalk, section: "Small Talk", italian: "Sto imparando l’italiano.", pronunciation: "sto imparando litaljano", german: "Ich lerne gerade Italienisch."),
        VocabularyItem(id: 164, category: .smallTalk, section: "Small Talk", italian: "Parlo solo un po’ d’italiano.", pronunciation: "parlo solo un po ditaljano", german: "Ich spreche nur ein bisschen Italienisch."),
        VocabularyItem(id: 165, category: .smallTalk, section: "Small Talk", italian: "Mi piace molto qui.", pronunciation: "mi pjatsche molto kwi", german: "Mir gefällt es hier sehr."),
        VocabularyItem(id: 166, category: .smallTalk, section: "Small Talk", italian: "È la mia prima volta qui.", pronunciation: "e la mia prima wolta kwi", german: "Ich bin zum ersten Mal hier."),
        VocabularyItem(id: 167, category: .smallTalk, section: "Small Talk", italian: "Da quanto tempo sei qui?", pronunciation: "da kwanto tempo säi kwi", german: "Wie lange bist du schon hier?"),
        VocabularyItem(id: 168, category: .smallTalk, section: "Small Talk", italian: "Quanto tempo resti qui?", pronunciation: "kwanto tempo resti kwi", german: "Wie lange bleibst du hier?"),
        VocabularyItem(id: 169, category: .smallTalk, section: "Small Talk", italian: "Sei di qui?", pronunciation: "säi di kwi", german: "Kommst du von hier?"),
        VocabularyItem(id: 170, category: .smallTalk, section: "Small Talk", italian: "Che bel posto!", pronunciation: "ke bel posto", german: "Was für ein schöner Ort!"),
        VocabularyItem(id: 171, category: .smallTalk, section: "Small Talk", italian: "Che bella giornata!", pronunciation: "ke bella dschornata", german: "Was für ein schöner Tag!"),
        VocabularyItem(id: 172, category: .smallTalk, section: "Small Talk", italian: "Lavoro in un ministero.", pronunciation: "laworo in un ministero", german: "Ich arbeite in einem Ministerium."),
        VocabularyItem(id: 173, category: .smallTalk, section: "Small Talk", italian: "E tu? Cosa fai?", pronunciation: "e tu, kosa fai", german: "Und du? Was machst du beruflich / was machst du?"),
        VocabularyItem(id: 174, category: .smallTalk, section: "Small Talk", italian: "Berlino è bella.", pronunciation: "Berlino e bella", german: "Berlin ist schön."),
        VocabularyItem(id: 175, category: .smallTalk, section: "Small Talk", italian: "Mi piace cucinare la pasta.", pronunciation: "mi pjatsche kutschinare la pasta", german: "Ich koche gerne Pasta."),
        VocabularyItem(id: 176, category: .smallTalk, section: "Small Talk", italian: "Voglio imparare l’italiano.", pronunciation: "wolljo imparare litaljano", german: "Ich will Italienisch lernen."),
        VocabularyItem(id: 177, category: .smallTalk, section: "Small Talk", italian: "Cosa insegni all’università?", pronunciation: "kosa insenji all-universita", german: "Was unterrichtest du an der Universität?"),
        VocabularyItem(id: 178, category: .smallTalk, section: "Small Talk", italian: "Quali materie insegni all’università?", pronunciation: "kwali materje insenji all-universita", german: "Welche Fächer unterrichtest du an der Universität?"),
        VocabularyItem(id: 179, category: .smallTalk, section: "Small Talk", italian: "Insegno tedesco.", pronunciation: "insenjo tedesko", german: "Ich unterrichte Deutsch."),
        VocabularyItem(id: 180, category: .everyday, section: "Telefonnummer · CBI 1–06", italian: "il numero di telefono", pronunciation: "il numero di telefono", german: "die Telefonnummer"),
        VocabularyItem(id: 181, category: .everyday, section: "Telefonnummer · CBI 1–06", italian: "Qual è il tuo numero di telefono?", pronunciation: "kwal e il tuo numero di telefono", german: "Wie lautet deine Telefonnummer?"),
        VocabularyItem(id: 182, category: .everyday, section: "Telefonnummer · CBI 1–06", italian: "Il mio numero di telefono è …", pronunciation: "il mio numero di telefono e", german: "Meine Telefonnummer ist …"),
        VocabularyItem(id: 183, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "la famiglia", pronunciation: "la familja", german: "die Familie"),
        VocabularyItem(id: 184, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mio padre", pronunciation: "mio padre", german: "mein Vater"),
        VocabularyItem(id: 185, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mia madre", pronunciation: "mia madre", german: "meine Mutter"),
        VocabularyItem(id: 186, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mio fratello", pronunciation: "mio fratello", german: "mein Bruder"),
        VocabularyItem(id: 187, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mia sorella", pronunciation: "mia sorella", german: "meine Schwester"),
        VocabularyItem(id: 188, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Ho un fratello.", pronunciation: "o un fratello", german: "Ich habe einen Bruder."),
        VocabularyItem(id: 189, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "ho", pronunciation: "o", german: "ich habe"),
        VocabularyItem(id: 190, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "hai", pronunciation: "ai", german: "du hast"),
        VocabularyItem(id: 191, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Hai fratelli o sorelle?", pronunciation: "ai fratelli o sorelle", german: "Hast du Brüder oder Schwestern?"),
        VocabularyItem(id: 192, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Hai un fratello?", pronunciation: "ai un fratello", german: "Hast du einen Bruder?"),
        VocabularyItem(id: 193, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Hai una sorella?", pronunciation: "ai una sorella", german: "Hast du eine Schwester?"),
        VocabularyItem(id: 194, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Ho una sorella.", pronunciation: "o una sorella", german: "Ich habe eine Schwester."),
        VocabularyItem(id: 195, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Ho due fratelli.", pronunciation: "o due fratelli", german: "Ich habe zwei Brüder."),
        VocabularyItem(id: 196, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "No, non ho fratelli.", pronunciation: "no, non o fratelli", german: "Nein, ich habe keine Brüder."),
        VocabularyItem(id: 197, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "No, non ho sorelle.", pronunciation: "no, non o sorelle", german: "Nein, ich habe keine Schwestern."),
        VocabularyItem(id: 198, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Non ho fratelli o sorelle.", pronunciation: "non o fratelli o sorelle", german: "Ich habe keine Brüder oder Schwestern."),
        VocabularyItem(id: 199, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mio figlio", pronunciation: "mio filjo", german: "mein Sohn"),
        VocabularyItem(id: 200, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mia figlia", pronunciation: "mia filja", german: "meine Tochter"),
        VocabularyItem(id: 201, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mio marito", pronunciation: "mio marito", german: "mein Ehemann"),
        VocabularyItem(id: 202, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "mia moglie", pronunciation: "mia mollje", german: "meine Ehefrau"),
        VocabularyItem(id: 203, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "il mio compagno", pronunciation: "il mio kompanjo", german: "mein Partner"),
        VocabularyItem(id: 204, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "la mia compagna", pronunciation: "la mia kompanja", german: "meine Partnerin"),
        VocabularyItem(id: 205, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questo è mio padre.", pronunciation: "kwesto e mio padre", german: "Das ist mein Vater."),
        VocabularyItem(id: 206, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questa è mia madre.", pronunciation: "kwesta e mia madre", german: "Das ist meine Mutter."),
        VocabularyItem(id: 207, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questo è mio figlio.", pronunciation: "kwesto e mio filjo", german: "Das ist mein Sohn."),
        VocabularyItem(id: 208, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questo è mio marito.", pronunciation: "kwesto e mio marito", german: "Das ist mein Ehemann."),
        VocabularyItem(id: 209, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questa è mia moglie.", pronunciation: "kwesta e mia mollje", german: "Das ist meine Ehefrau."),
        VocabularyItem(id: 210, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questo è il mio compagno.", pronunciation: "kwesto e il mio kompanjo", german: "Das ist mein Partner."),
        VocabularyItem(id: 211, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Questa è la mia compagna.", pronunciation: "kwesta e la mia kompanja", german: "Das ist meine Partnerin."),
        VocabularyItem(id: 212, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Come si chiama tua madre?", pronunciation: "kome si kjama tua madre", german: "Wie heißt deine Mutter?"),
        VocabularyItem(id: 213, category: .family, section: "Familie · CBI 1–05 und 1–06", italian: "Si chiama …", pronunciation: "si kjama", german: "Er / Sie heißt …"),
        VocabularyItem(id: 214, category: .numbers, section: "Zahlen", italian: "zero", pronunciation: "dsero", german: "0 · null"),
        VocabularyItem(id: 215, category: .numbers, section: "Zahlen", italian: "uno", pronunciation: "uno", german: "1 · eins"),
        VocabularyItem(id: 216, category: .numbers, section: "Zahlen", italian: "due", pronunciation: "due", german: "2 · zwei"),
        VocabularyItem(id: 217, category: .numbers, section: "Zahlen", italian: "tre", pronunciation: "tre", german: "3 · drei"),
        VocabularyItem(id: 218, category: .numbers, section: "Zahlen", italian: "quattro", pronunciation: "kwattro", german: "4 · vier"),
        VocabularyItem(id: 219, category: .numbers, section: "Zahlen", italian: "cinque", pronunciation: "tschinkwe", german: "5 · fünf"),
        VocabularyItem(id: 220, category: .numbers, section: "Zahlen", italian: "sei", pronunciation: "säi", german: "6 · sechs"),
        VocabularyItem(id: 221, category: .numbers, section: "Zahlen", italian: "sette", pronunciation: "sette", german: "7 · sieben"),
        VocabularyItem(id: 222, category: .numbers, section: "Zahlen", italian: "otto", pronunciation: "otto", german: "8 · acht"),
        VocabularyItem(id: 223, category: .numbers, section: "Zahlen", italian: "nove", pronunciation: "nowe", german: "9 · neun"),
        VocabularyItem(id: 224, category: .numbers, section: "Zahlen", italian: "dieci", pronunciation: "djättschi", german: "10 · zehn"),
        VocabularyItem(id: 225, category: .numbers, section: "Zahlen", italian: "undici", pronunciation: "unditschi", german: "11 · elf"),
        VocabularyItem(id: 226, category: .numbers, section: "Zahlen", italian: "dodici", pronunciation: "doditschi", german: "12 · zwölf"),
        VocabularyItem(id: 227, category: .numbers, section: "Zahlen", italian: "tredici", pronunciation: "treditschi", german: "13 · dreizehn"),
        VocabularyItem(id: 228, category: .numbers, section: "Zahlen", italian: "quattordici", pronunciation: "kwattorditschi", german: "14 · vierzehn"),
        VocabularyItem(id: 229, category: .numbers, section: "Zahlen", italian: "quindici", pronunciation: "kwinditschi", german: "15 · fünfzehn"),
        VocabularyItem(id: 230, category: .numbers, section: "Zahlen", italian: "sedici", pronunciation: "seditschi", german: "16 · sechzehn"),
        VocabularyItem(id: 231, category: .numbers, section: "Zahlen", italian: "diciassette", pronunciation: "ditschassette", german: "17 · siebzehn"),
        VocabularyItem(id: 232, category: .numbers, section: "Zahlen", italian: "diciotto", pronunciation: "ditschotto", german: "18 · achtzehn"),
        VocabularyItem(id: 233, category: .numbers, section: "Zahlen", italian: "diciannove", pronunciation: "ditschannowe", german: "19 · neunzehn"),
        VocabularyItem(id: 234, category: .numbers, section: "Zahlen", italian: "venti", pronunciation: "wenti", german: "20 · zwanzig"),
        VocabularyItem(id: 235, category: .numbers, section: "Zahlen", italian: "ventuno", pronunciation: "wentuno", german: "21 · einundzwanzig"),
        VocabularyItem(id: 236, category: .numbers, section: "Zahlen", italian: "ventidue", pronunciation: "wentidue", german: "22 · zweiundzwanzig"),
        VocabularyItem(id: 237, category: .numbers, section: "Zahlen", italian: "ventitré", pronunciation: "wentitre", german: "23 · dreiundzwanzig"),
        VocabularyItem(id: 238, category: .numbers, section: "Zahlen", italian: "ventiquattro", pronunciation: "wentikwattro", german: "24 · vierundzwanzig"),
        VocabularyItem(id: 239, category: .numbers, section: "Zahlen", italian: "venticinque", pronunciation: "wentitschinkwe", german: "25 · fünfundzwanzig"),
        VocabularyItem(id: 240, category: .numbers, section: "Zahlen", italian: "ventisei", pronunciation: "wentisäi", german: "26 · sechsundzwanzig"),
        VocabularyItem(id: 241, category: .numbers, section: "Zahlen", italian: "ventisette", pronunciation: "wentisette", german: "27 · siebenundzwanzig"),
        VocabularyItem(id: 242, category: .numbers, section: "Zahlen", italian: "ventotto", pronunciation: "wentotto", german: "28 · achtundzwanzig"),
        VocabularyItem(id: 243, category: .numbers, section: "Zahlen", italian: "ventinove", pronunciation: "wentinowe", german: "29 · neunundzwanzig"),
        VocabularyItem(id: 244, category: .numbers, section: "Zahlen", italian: "trenta", pronunciation: "trenta", german: "30 · dreißig"),
        VocabularyItem(id: 245, category: .numbers, section: "Zahlen", italian: "quaranta", pronunciation: "kwaranta", german: "40 · vierzig"),
        VocabularyItem(id: 246, category: .numbers, section: "Zahlen", italian: "cinquanta", pronunciation: "tschinkwanta", german: "50 · fünfzig"),
        VocabularyItem(id: 247, category: .numbers, section: "Zahlen", italian: "sessanta", pronunciation: "sessanta", german: "60 · sechzig"),
        VocabularyItem(id: 248, category: .numbers, section: "Zahlen", italian: "settanta", pronunciation: "settanta", german: "70 · siebzig"),
        VocabularyItem(id: 249, category: .numbers, section: "Zahlen", italian: "ottanta", pronunciation: "ottanta", german: "80 · achtzig"),
        VocabularyItem(id: 250, category: .numbers, section: "Zahlen", italian: "novanta", pronunciation: "nowanta", german: "90 · neunzig"),
        VocabularyItem(id: 251, category: .numbers, section: "Zahlen", italian: "cento", pronunciation: "tschento", german: "100 · einhundert"),
        VocabularyItem(id: 252, category: .numbers, section: "Zahlen", italian: "duecento", pronunciation: "duetschento", german: "200 · zweihundert"),
        VocabularyItem(id: 253, category: .numbers, section: "Zahlen", italian: "trecento", pronunciation: "tretschento", german: "300 · dreihundert"),
        VocabularyItem(id: 254, category: .numbers, section: "Zahlen", italian: "quattrocento", pronunciation: "kwattrotschento", german: "400 · vierhundert"),
        VocabularyItem(id: 255, category: .numbers, section: "Zahlen", italian: "cinquecento", pronunciation: "tschinkwetschento", german: "500 · fünfhundert"),
        VocabularyItem(id: 256, category: .numbers, section: "Zahlen", italian: "seicento", pronunciation: "säitschento", german: "600 · sechshundert"),
        VocabularyItem(id: 257, category: .numbers, section: "Zahlen", italian: "settecento", pronunciation: "settetschento", german: "700 · siebenhundert"),
        VocabularyItem(id: 258, category: .numbers, section: "Zahlen", italian: "ottocento", pronunciation: "ottotschento", german: "800 · achthundert"),
        VocabularyItem(id: 259, category: .numbers, section: "Zahlen", italian: "novecento", pronunciation: "nowetschento", german: "900 · neunhundert"),
        VocabularyItem(id: 260, category: .numbers, section: "Zahlen", italian: "mille", pronunciation: "mille", german: "1.000 · eintausend"),
        VocabularyItem(id: 261, category: .numbers, section: "Zahlen", italian: "duemila", pronunciation: "duemila", german: "2.000 · zweitausend"),
        VocabularyItem(id: 262, category: .numbers, section: "Zahlen", italian: "tremila", pronunciation: "tremila", german: "3.000 · dreitausend"),
        VocabularyItem(id: 263, category: .numbers, section: "Zahlen", italian: "quattromila", pronunciation: "kwattromila", german: "4.000 · viertausend"),
        VocabularyItem(id: 264, category: .numbers, section: "Zahlen", italian: "cinquemila", pronunciation: "tschinkwemila", german: "5.000 · fünftausend"),
        VocabularyItem(id: 265, category: .numbers, section: "Zahlen", italian: "seimila", pronunciation: "säimila", german: "6.000 · sechstausend"),
        VocabularyItem(id: 266, category: .numbers, section: "Zahlen", italian: "settemila", pronunciation: "settemila", german: "7.000 · siebentausend"),
        VocabularyItem(id: 267, category: .numbers, section: "Zahlen", italian: "ottomila", pronunciation: "ottomila", german: "8.000 · achttausend"),
        VocabularyItem(id: 268, category: .numbers, section: "Zahlen", italian: "novemila", pronunciation: "nowemila", german: "9.000 · neuntausend"),
        VocabularyItem(id: 269, category: .numbers, section: "Zahlen", italian: "diecimila", pronunciation: "djättschimila", german: "10.000 · zehntausend"),
    ]

    static let lessons: [ItalianLesson] = [
        ItalianLesson(
            id: 1,
            shortTitle: "Erste Begegnung",
            title: "Erste Begegnung – Begrüßen und Befinden",
            goal: "jemanden begrüßen, fragen, wie es ihm oder ihr geht, und kurz antworten.",
            icon: "hand.wave.fill",
            phrases: [
                LessonPhrase(id: "1-p1", italian: "Buongiorno!", pronunciation: "buon-dschorno", german: "Guten Morgen! / Guten Tag!"),
                LessonPhrase(id: "1-p2", italian: "Buon pomeriggio!", pronunciation: "buon pomeriddscho", german: "Guten Nachmittag!"),
                LessonPhrase(id: "1-p3", italian: "Buonasera!", pronunciation: "buona-sera", german: "Guten Abend!"),
                LessonPhrase(id: "1-p4", italian: "Buonanotte!", pronunciation: "buona-notte", german: "Gute Nacht!"),
                LessonPhrase(id: "1-p5", italian: "Ciao!", pronunciation: "tschau", german: "Hallo! / Tschüss! – informell"),
                LessonPhrase(id: "1-p6", italian: "Come stai?", pronunciation: "kome stai", german: "Wie geht es dir?"),
                LessonPhrase(id: "1-p7", italian: "Come sta?", pronunciation: "kome sta", german: "Wie geht es Ihnen?"),
                LessonPhrase(id: "1-p8", italian: "Bene, grazie. E tu?", pronunciation: "bene, gratsje. e tu", german: "Gut, danke. Und dir?"),
                LessonPhrase(id: "1-p9", italian: "Molto bene.", pronunciation: "molto bene", german: "Sehr gut."),
                LessonPhrase(id: "1-p10", italian: "Così così.", pronunciation: "kosi kosi", german: "So lala."),
                LessonPhrase(id: "1-p11", italian: "Non c’è male.", pronunciation: "non tsche male", german: "Nicht schlecht."),
                LessonPhrase(id: "1-p12", italian: "Male.", pronunciation: "male", german: "Schlecht."),
                LessonPhrase(id: "1-p13", italian: "Sono un po’ stanco.", pronunciation: "sono un po stanko", german: "Ich bin ein bisschen müde."),
                LessonPhrase(id: "1-p14", italian: "Ho troppo lavoro.", pronunciation: "o troppo laworo", german: "Ich habe zu viel Arbeit."),
            ],
            notes: [
                LessonNote(id: "1-n1", title: "Verstehen: Warum buon und buona?", body: "Buono bedeutet „gut“. Vor einem männlichen Wort steht hier buon , vor einem weiblichen buona : il giorno → buongiorno · il pomeriggio → buon pomeriggio · la sera → buonasera · la notte → buonanotte"),
                LessonNote(id: "1-n2", title: "Verstehen: stai oder sta?", body: "Come stai? benutzt du bei Freunden, Familie und Menschen, die du duzt. Come sta? ist die höfliche Form für Menschen, die du siezt. Auch die Rückfrage passt sich an: E tu? = Und du? · E Lei? = Und Sie?"),
                LessonNote(id: "1-n3", title: "Persönlich antworten", body: "Als Mann sagst du stanco , als Frau stanca . Für dich passt also: Sono un po’ stanco. Un po’ bedeutet „ein bisschen“, troppo bedeutet „zu viel“."),
            ],
            memories: [
                "Merksatz: Bei Come stai? hörst du am Ende das i – das ist die Form für du .",
            ],
            dialogue: [
                DialogueLine(id: "1-d1", speaker: "A", italian: "Ciao! Come stai?", german: "Hallo! Wie geht es dir?"),
                DialogueLine(id: "1-d2", speaker: "B", italian: "Sono un po’ stanco. Ho troppo lavoro. E tu?", german: "Ich bin ein bisschen müde. Ich habe zu viel Arbeit. Und dir?"),
                DialogueLine(id: "1-d3", speaker: "A", italian: "Molto bene, grazie!", german: "Sehr gut, danke!"),
            ]
        ),
        ItalianLesson(
            id: 2,
            shortTitle: "Kontaktdaten",
            title: "Kontaktdaten – Name, Alphabet und Telefonnummer",
            goal: "nach einem Namen und einer Telefonnummer fragen, dich vorstellen, Namen buchstabieren und Ziffern sicher nennen.",
            icon: "person.text.rectangle.fill",
            phrases: [
                LessonPhrase(id: "2-p1", italian: "Come ti chiami?", pronunciation: "kome ti kjami", german: "Wie heißt du? – informell"),
                LessonPhrase(id: "2-p2", italian: "Come si chiama?", pronunciation: "kome si kjama", german: "Wie heißen Sie? – höflich"),
                LessonPhrase(id: "2-p3", italian: "Mi chiamo Tobias.", pronunciation: "mi kjamo Tobias", german: "Ich heiße Tobias."),
                LessonPhrase(id: "2-p4", italian: "Piacere!", pronunciation: "pjatschere", german: "Freut mich!"),
                LessonPhrase(id: "2-p5", italian: "Il numero di telefono.", pronunciation: "il numero di telefono", german: "Die Telefonnummer."),
                LessonPhrase(id: "2-p6", italian: "Qual è il tuo numero di telefono?", pronunciation: "kwal e il tuo numero di telefono", german: "Wie lautet deine Telefonnummer?"),
                LessonPhrase(id: "2-p7", italian: "Il mio numero di telefono è …", pronunciation: "il mio numero di telefono e", german: "Meine Telefonnummer ist …"),
            ],
            notes: [
                LessonNote(id: "2-n1", title: "Verstehen: mi, ti und si", body: "Bei chiamarsi („heißen“) verändert sich das kleine Wort vor dem Verb: mi chiamo = ich heiße · ti chiami = du heißt · si chiama = Sie heißen / er oder sie heißt Darum lautet die Frage Come ti chiami? , aber deine Antwort Mi chiamo Tobias."),
                LessonNote(id: "2-n2", title: "21 Buchstaben und ihre Namen", body: "Buchstaben So heißen sie auf Italienisch A – B – C – D – E a – bi – ci – di – e F – G – H – I effe – gi – acca – i L – M – N – O elle – emme – enne – o P – Q – R – S – T pi – cu – erre – esse – ti U – V – Z u – vi / vu – zeta Aussprachehilfe: a – bi – tschi – di – e · effe – dschi – akka – i · elle – emme – enne – o · pi – ku – erre – esse – ti · u – wi/wu – dzeta. Besonderheit: J, K, W, X und Y gehören nicht zum klassischen italienischen Alphabet. Sie kommen hauptsächlich in Fremdwörtern und Namen vor: i lunga, kappa, doppia vu, ics, ipsilon ."),
                LessonNote(id: "2-n3", title: "Ziffern einzeln sprechen", body: "zero · uno · due · tre · quattro · cinque · sei · sette · otto · nove · dieci Bei einer Telefonnummer sprichst du die Ziffern normalerweise einzeln. Achte bei quattro , sette und otto auf die hörbaren Doppelkonsonanten."),
            ],
            memories: [
                "Dein Satz: Die Frage beginnt mit ti („dich“), deine Antwort mit mi („mich“): Come ti chiami? – Mi chiamo Tobias.",
                "Merksatz: Nach I geht es direkt mit L weiter – J und K sind Zusatzbuchstaben. Nach V folgt im klassischen Alphabet direkt Z .",
            ],
            dialogue: [
                DialogueLine(id: "2-d1", speaker: "A", italian: "Buongiorno! Come ti chiami?", german: "Guten Tag! Wie heißt du?"),
                DialogueLine(id: "2-d2", speaker: "B", italian: "Mi chiamo Tobias. E tu?", german: "Ich heiße Tobias. Und du?"),
                DialogueLine(id: "2-d3", speaker: "A", italian: "Mi chiamo Luca. Piacere!", german: "Ich heiße Luca. Freut mich!"),
                DialogueLine(id: "2-d4", speaker: "B", italian: "Piacere mio!", german: "Ganz meinerseits!"),
                DialogueLine(id: "2-d5", speaker: "A", italian: "Come ti chiami?", german: "Wie heißt du?"),
                DialogueLine(id: "2-d6", speaker: "B", italian: "Mi chiamo Tobias.", german: "Ich heiße Tobias."),
                DialogueLine(id: "2-d7", speaker: "A", italian: "Qual è il tuo numero di telefono?", german: "Wie lautet deine Telefonnummer?"),
                DialogueLine(id: "2-d8", speaker: "B", italian: "Il mio numero di telefono è …", german: "Meine Telefonnummer ist …"),
            ]
        ),
        ItalianLesson(
            id: 3,
            shortTitle: "Herkunft & essere",
            title: "Woher kommst du? – Herkunft, Nationalität und „essere“",
            goal: "nach der Herkunft fragen, deine Stadt und Nationalität nennen und das Verb essere für eine oder mehrere Personen verwenden.",
            icon: "globe.europe.africa.fill",
            phrases: [
                LessonPhrase(id: "3-p1", italian: "Di dove sei?", pronunciation: "di dowe säi", german: "Woher kommst du? – informell"),
                LessonPhrase(id: "3-p2", italian: "Di dov’è?", pronunciation: "di dowe", german: "Woher kommen Sie? – höflich"),
                LessonPhrase(id: "3-p3", italian: "Sono di Berlino.", pronunciation: "sono di berlino", german: "Ich komme aus Berlin."),
                LessonPhrase(id: "3-p4", italian: "E Lei? Di dov’è?", pronunciation: "e läi, di dowe", german: "Und Sie? Woher kommen Sie?"),
                LessonPhrase(id: "3-p5", italian: "Di dove siete?", pronunciation: "di dowe sjete", german: "Woher kommt ihr? / Woher kommen Sie? – Mehrzahl"),
                LessonPhrase(id: "3-p6", italian: "Siamo di Berlino.", pronunciation: "sjamo di berlino", german: "Wir kommen aus Berlin."),
                LessonPhrase(id: "3-p7", italian: "io sono", pronunciation: "io sono", german: "ich bin"),
                LessonPhrase(id: "3-p8", italian: "tu sei", pronunciation: "tu säi", german: "du bist"),
                LessonPhrase(id: "3-p9", italian: "lui / lei / Lei è", pronunciation: "lui / läi / läi ä", german: "er / sie ist · Sie sind"),
                LessonPhrase(id: "3-p10", italian: "noi siamo", pronunciation: "noi sjamo", german: "wir sind"),
                LessonPhrase(id: "3-p11", italian: "voi siete", pronunciation: "voi sjete", german: "ihr seid · Sie sind (Mehrzahl)"),
                LessonPhrase(id: "3-p12", italian: "loro sono", pronunciation: "loro sono", german: "sie sind"),
            ],
            notes: [
                LessonNote(id: "3-n1", title: "Personalpronomen: Einzahl und Mehrzahl", body: "Einzahl Mehrzahl io = ich noi = wir tu = du voi = ihr / Sie (Mehrzahl) lui / lei / Lei = er / sie / Sie loro = sie Lei mit großem L ist die höfliche Anrede für eine Person. lei mit kleinem l bedeutet „sie“."),
                LessonNote(id: "3-n2", title: "Essere in der Einzahl – zuerst diese drei Formen", body: "Essere („sein“) ist unregelmäßig. Die Formen sehen also unterschiedlich aus und werden am besten als feste Paare gelernt: io sono io sono ich bin tu sei tu säi du bist lui / lei / Lei è lui / läi / läi ä er / sie ist · Sie sind IO Io sono di Berlino. Ich komme aus Berlin. TU Tu sei di Roma. Du kommst aus Rom. LUI Lui è di Milano. Er kommt aus Mailand. Normalerweise lässt man io, tu, lui oder lei weg, wenn klar ist, wer gemeint ist. Zum Lernen helfen die Pronomen zunächst dabei, die Formen zuzuordnen."),
                LessonNote(id: "3-n3", title: "Essere in der Mehrzahl – wenn du über mehrere Personen sprichst", body: "Auch die Formen der Mehrzahl sind unregelmäßig. Lerne sie deshalb ebenfalls als feste Paare: noi siamo noi sjamo wir sind voi siete voi sjete ihr seid · Sie sind (Mehrzahl) loro sono loro sono sie sind NOI Noi siamo di Berlino. Wir kommen aus Berlin. VOI Voi siete di Roma. Ihr kommt aus Rom. LORO Loro sono di Milano. Sie kommen aus Mailand. Auch hier kann das Pronomen meist wegfallen: Siamo di Berlino. ist im Gespräch natürlicher als Noi siamo di Berlino."),
                LessonNote(id: "3-n4", title: "Das Verb essere – sein", body: "Person Form Deutsch io sono ich bin tu sei du bist lui / lei / Lei è er / sie ist · Sie sind noi siamo wir sind voi siete ihr seid · Sie sind loro sono sie sind Das Pronomen kann im Italienischen oft wegfallen, weil die Verbform schon zeigt, wer gemeint ist: Sono di Berlino. statt Io sono di Berlino."),
                LessonNote(id: "3-n5", title: "Verstehen: Stadt oder Nationalität?", body: "Für eine Stadt benutzt du sono di : Sono di Berlino. – Ich komme aus Berlin. Für die Nationalität benutzt du sono ohne di : Sono tedesco. – Ich bin Deutscher. Sono bedeutet „ich bin“. Das persönliche io lässt man normalerweise weg, weil die Verbform bereits zeigt, wer gemeint ist."),
                LessonNote(id: "3-n6", title: "Meistens: -o männlich, -a weiblich", body: "Männlich Weiblich Deutsch tedesco tedesca deutsch italiano italiana italienisch americano americana amerikanisch spagnolo spagnola spanisch Nationalitäten auf -ese haben für Mann und Frau dieselbe Form: francese , scozzese , irlandese ."),
            ],
            memories: [
                "Deine kurze Vorstellung: Mi chiamo Tobias, sono tedesco e vengo da Berlino, in Germania.",
                "Merksatz: Sono di Berlino nennt den Ort. Sono tedesco nennt die Nationalität. Sono kann außerdem „ich bin“ oder „sie sind“ bedeuten – der Zusammenhang macht klar, wer gemeint ist.",
            ],
            dialogue: [
                DialogueLine(id: "3-d1", speaker: "IO", italian: "Io sono di Berlino.", german: "Ich komme aus Berlin."),
                DialogueLine(id: "3-d2", speaker: "TU", italian: "Tu sei di Roma.", german: "Du kommst aus Rom."),
                DialogueLine(id: "3-d3", speaker: "LUI", italian: "Lui è di Milano.", german: "Er kommt aus Mailand."),
                DialogueLine(id: "3-d4", speaker: "NOI", italian: "Noi siamo di Berlino.", german: "Wir kommen aus Berlin."),
                DialogueLine(id: "3-d5", speaker: "VOI", italian: "Voi siete di Roma.", german: "Ihr kommt aus Rom."),
                DialogueLine(id: "3-d6", speaker: "LORO", italian: "Loro sono di Milano.", german: "Sie kommen aus Mailand."),
                DialogueLine(id: "3-d7", speaker: "A", italian: "Di dove sei?", german: "Woher kommst du?"),
                DialogueLine(id: "3-d8", speaker: "B", italian: "Sono di Berlino. Sono tedesco. E tu?", german: "Ich komme aus Berlin. Ich bin Deutscher. Und du?"),
                DialogueLine(id: "3-d9", speaker: "A", italian: "Sono di Torino. Sono italiano.", german: "Ich komme aus Turin. Ich bin Italiener."),
            ]
        ),
        ItalianLesson(
            id: 4,
            shortTitle: "Wohnort & abitare",
            title: "Wo wohnst du? – Wohnort und „abitare“",
            goal: "nach dem Wohnort fragen, Stadt und Land nennen und sagen, wo du nicht wohnst.",
            icon: "house.fill",
            phrases: [
                LessonPhrase(id: "4-p1", italian: "Dove abiti?", pronunciation: "dowe abiti", german: "Wo wohnst du? – informell"),
                LessonPhrase(id: "4-p2", italian: "Dove abita?", pronunciation: "dowe abita", german: "Wo wohnen Sie? – höflich"),
                LessonPhrase(id: "4-p3", italian: "Abito a Berlino.", pronunciation: "abito a berlino", german: "Ich wohne in Berlin."),
                LessonPhrase(id: "4-p4", italian: "Abito in Germania.", pronunciation: "abito in dschermania", german: "Ich wohne / lebe in Deutschland."),
                LessonPhrase(id: "4-p5", italian: "io abito", pronunciation: "io abito", german: "ich wohne"),
                LessonPhrase(id: "4-p6", italian: "tu abiti", pronunciation: "tu abiti", german: "du wohnst"),
                LessonPhrase(id: "4-p7", italian: "lui / lei / Lei abita", pronunciation: "lui / läi / läi abita", german: "er / sie wohnt · Sie wohnen"),
                LessonPhrase(id: "4-p8", italian: "noi abitiamo", pronunciation: "noi abitjamo", german: "wir wohnen"),
                LessonPhrase(id: "4-p9", italian: "voi abitate", pronunciation: "voi abitate", german: "ihr wohnt · Sie wohnen (Mehrzahl)"),
                LessonPhrase(id: "4-p10", italian: "loro abitano", pronunciation: "loro abitano", german: "sie wohnen"),
                LessonPhrase(id: "4-p11", italian: "Abito a Firenze, in Italia.", pronunciation: "abito a firentse, in italja", german: "Ich wohne in Florenz, in Italien."),
                LessonPhrase(id: "4-p12", italian: "Abito a Glasgow, in Scozia.", pronunciation: "abito a gläsgou, in skotsja", german: "Ich wohne in Glasgow, in Schottland."),
                LessonPhrase(id: "4-p13", italian: "Abito a Londra, in Inghilterra.", pronunciation: "abito a londra, in ingilterra", german: "Ich wohne in London, in England."),
                LessonPhrase(id: "4-p14", italian: "Abito a Dublino, in Irlanda.", pronunciation: "abito a dublino, in irlanda", german: "Ich wohne in Dublin, in Irland."),
                LessonPhrase(id: "4-p15", italian: "Abito a New York, negli Stati Uniti.", pronunciation: "abito a nju jork, nellji stati uniti", german: "Ich wohne in New York, in den USA."),
                LessonPhrase(id: "4-p16", italian: "Abito a Sydney, in Australia.", pronunciation: "abito a sidni, in australia", german: "Ich wohne in Sydney, in Australien."),
                LessonPhrase(id: "4-p17", italian: "Abito a Roma, in Italia. E tu?", pronunciation: "abito a roma, in italja. e tu", german: "Ich wohne in Rom, in Italien. Und du?"),
                LessonPhrase(id: "4-p18", italian: "Abito in Scozia, a Edimburgo.", pronunciation: "abito in skotsja, a edimburgo", german: "Ich wohne in Schottland, in Edinburgh."),
                LessonPhrase(id: "4-p19", italian: "Non abito a Milano.", pronunciation: "non abito a milano", german: "Ich wohne nicht in Mailand."),
                LessonPhrase(id: "4-p20", italian: "Non sono italiano.", pronunciation: "non sono italjano", german: "Ich bin kein Italiener."),
                LessonPhrase(id: "4-p21", italian: "Non voglio un caffè.", pronunciation: "non wolljo un kaffe", german: "Ich möchte keinen Kaffee."),
                LessonPhrase(id: "4-p22", italian: "Non sto bene.", pronunciation: "non sto bene", german: "Mir geht es nicht gut."),
            ],
            notes: [
                LessonNote(id: "4-n1", title: "Abitare – wohnen · alle Formen", body: "Die Endung zeigt, wer wohnt. Die drei Formen der Einzahl und die drei Formen der Mehrzahl folgen einem regelmäßigen Muster: io abito io abito ich wohne tu abiti tu abiti du wohnst lui / lei / Lei abita lui / läi / läi abita er / sie wohnt · Sie wohnen noi abitiamo noi abitjamo wir wohnen voi abitate voi abitate ihr wohnt · Sie wohnen (Mehrzahl) loro abitano loro abitano sie wohnen IO Io abito a Berlino. Ich wohne in Berlin. TU Tu abiti a Roma. Du wohnst in Rom. LEI Lei abita a Milano. Sie wohnen in Mailand. NOI Noi abitiamo a Berlino. Wir wohnen in Berlin. VOI Voi abitate a Roma. Ihr wohnt in Rom. LORO Tom e Mark abitano in Germania. Tom und Mark wohnen in Deutschland. Tom e Mark sind mehrere Personen und funktionieren deshalb wie loro : Tom e Mark abitano . Im Gespräch fällt ein Pronomen meistens weg, wenn die Verbform schon zeigt, wer gemeint ist."),
                LessonNote(id: "4-n2", title: "Aussage oder Frage? Die Wortfolge bleibt gleich", body: "Im Italienischen wird eine Aussage meist nur durch die steigende Stimme zur Frage. Es gibt kein zusätzliches Hilfsverb wie im Englischen und die Wörter werden nicht umgestellt. Person Aussage Frage io Io abito in Italia. Abito in Italia? tu Tu abiti in Italia. Abiti in Italia? lui / lei Lui / lei abita in Italia. Abita in Italia? Lei Lei abita in Italia. Abita in Italia? noi Noi abitiamo in Italia. Abitiamo in Italia? voi Voi abitate in Italia. Abitate in Italia? loro Loro abitano in Italia. Abitano in Italia? Die Pronomen dienen hier zur Orientierung. Natürlicher sind meistens die kurzen Formen: Abiti in Italia? , Abitate in Italia? oder Abitano in Italia? Der Zusammenhang zeigt, wer gemeint ist."),
                LessonNote(id: "4-n3", title: "Verstehen: a bei Städten, in bei Ländern", body: "Vor einer Stadt steht normalerweise a : Abito a Berlino. Vor einem Land steht normalerweise in : Abito in Germania. Beides lässt sich verbinden: Abito a Berlino, in Germania."),
                LessonNote(id: "4-n4", title: "Verstehen: Verneinen mit non", body: "Non bedeutet meist „nicht“ und steht direkt vor dem Verb. Du musst das Verb dafür nicht verändern. Non abito a Milano. non abito a milano Ich wohne nicht in Mailand. Non sono italiano. non sono italjano Ich bin kein Italiener. Non voglio un caffè. non wolljo un kaffe Ich möchte keinen Kaffee. Non sto bene. non sto bene Mir geht es nicht gut. No heißt allein „Nein“. Non verneint dagegen einen Satz: No, non abito a Milano. – Nein, ich wohne nicht in Mailand. Bei einer Ja-Nein-Frage bleibt die Wortfolge einfach: Abiti a Milano? – Wohnst du in Mailand? Die vollständige Antwort aus der Folge lautet: No, non abito a Milano. Abito a Trieste."),
            ],
            memories: [
                "Merksatz: a Berlino für eine Stadt, in Germania für ein Land.",
            ],
            dialogue: [
                DialogueLine(id: "4-d1", speaker: "IO", italian: "Io abito a Berlino.", german: "Ich wohne in Berlin."),
                DialogueLine(id: "4-d2", speaker: "TU", italian: "Tu abiti a Roma.", german: "Du wohnst in Rom."),
                DialogueLine(id: "4-d3", speaker: "LEI", italian: "Lei abita a Milano.", german: "Sie wohnen in Mailand."),
                DialogueLine(id: "4-d4", speaker: "NOI", italian: "Noi abitiamo a Berlino.", german: "Wir wohnen in Berlin."),
                DialogueLine(id: "4-d5", speaker: "VOI", italian: "Voi abitate a Roma.", german: "Ihr wohnt in Rom."),
                DialogueLine(id: "4-d6", speaker: "LORO", italian: "Tom e Mark abitano in Germania.", german: "Tom und Mark wohnen in Deutschland."),
                DialogueLine(id: "4-d7", speaker: "A", italian: "Dove abiti?", german: "Wo wohnst du?"),
                DialogueLine(id: "4-d8", speaker: "B", italian: "Abito a Berlino, in Germania. E tu?", german: "Ich wohne in Berlin, in Deutschland. Und du?"),
                DialogueLine(id: "4-d9", speaker: "A", italian: "Abito a Roma, in Italia.", german: "Ich wohne in Rom, in Italien."),
            ]
        ),
        ItalianLesson(
            id: 5,
            shortTitle: "Familie",
            title: "Meine Familie – Personen vorstellen und Geschwister",
            goal: "Familienmitglieder vorstellen, nach Geschwistern fragen und mit ho , hai und non ho antworten.",
            icon: "figure.2.and.child.holdinghands",
            phrases: [
                LessonPhrase(id: "5-p1", italian: "Questo è mio padre.", pronunciation: "kwesto e mio padre", german: "Das ist mein Vater."),
                LessonPhrase(id: "5-p2", italian: "Questa è mia madre.", pronunciation: "kwesta e mia madre", german: "Das ist meine Mutter."),
                LessonPhrase(id: "5-p3", italian: "Questo è mio figlio.", pronunciation: "kwesto e mio filjo", german: "Das ist mein Sohn."),
                LessonPhrase(id: "5-p4", italian: "Questa è mia moglie.", pronunciation: "kwesta e mia mollje", german: "Das ist meine Ehefrau."),
                LessonPhrase(id: "5-p5", italian: "Come si chiama tua madre?", pronunciation: "kome si kjama tua madre", german: "Wie heißt deine Mutter?"),
                LessonPhrase(id: "5-p6", italian: "Si chiama …", pronunciation: "si kjama", german: "Er / Sie heißt …"),
                LessonPhrase(id: "5-p7", italian: "Ho un fratello.", pronunciation: "o un fratello", german: "Ich habe einen Bruder."),
                LessonPhrase(id: "5-p8", italian: "Hai fratelli o sorelle?", pronunciation: "ai fratelli o sorelle", german: "Hast du Brüder oder Schwestern?"),
                LessonPhrase(id: "5-p9", italian: "Hai un fratello?", pronunciation: "ai un fratello", german: "Hast du einen Bruder?"),
                LessonPhrase(id: "5-p10", italian: "Hai una sorella?", pronunciation: "ai una sorella", german: "Hast du eine Schwester?"),
                LessonPhrase(id: "5-p11", italian: "Ho una sorella.", pronunciation: "o una sorella", german: "Ich habe eine Schwester."),
                LessonPhrase(id: "5-p12", italian: "Ho due fratelli.", pronunciation: "o due fratelli", german: "Ich habe zwei Brüder."),
                LessonPhrase(id: "5-p13", italian: "No, non ho fratelli.", pronunciation: "no, non o fratelli", german: "Nein, ich habe keine Brüder."),
                LessonPhrase(id: "5-p14", italian: "No, non ho sorelle.", pronunciation: "no, non o sorelle", german: "Nein, ich habe keine Schwestern."),
                LessonPhrase(id: "5-p15", italian: "Non ho fratelli o sorelle.", pronunciation: "non o fratelli o sorelle", german: "Ich habe keine Brüder oder Schwestern."),
            ],
            notes: [
                LessonNote(id: "5-n1", title: "Verstehen: mio bei männlichen, mia bei weiblichen Wörtern", body: "Mio und mia bedeuten beide „mein/meine“. Welche Form du benutzt, richtet sich nach dem italienischen Wort , nicht nach der Person, die spricht. Männlich Weiblich Deutsch mio padre mia madre mein Vater / meine Mutter mio fratello mia sorella mein Bruder / meine Schwester mio figlio mia figlia mein Sohn / meine Tochter mio marito mia moglie mein Ehemann / meine Ehefrau Merke: Die Endung hilft dir oft: -o → mio , -a → mia . Das ist eine gute Lernhilfe, aber keine allgemeine Regel für jedes italienische Substantiv."),
                LessonNote(id: "5-n2", title: "Verstehen: questo oder questa?", body: "Questo verwendest du hier mit einem männlichen Wort: Questo è mio padre. Questa verwendest du hier mit einem weiblichen Wort: Questa è mia madre. Das Muster kennst du schon: Im Italienischen passen sich viele kleine Wörter an männlich/weiblich an – ähnlich wie bei buon/buona aus Lektion 1–02."),
                LessonNote(id: "5-n3", title: "Verstehen: mi chiamo und si chiama", body: "Mi chiamo Tobias. = Ich heiße Tobias. Si chiama Luca. = Er heißt Luca. / Sie heißt Luca. Das si kennst du schon aus der höflichen Frage Come si chiama? . Der Kontext zeigt dir, ob „Sie heißen“ oder „er/sie heißt“ gemeint ist."),
                LessonNote(id: "5-n4", title: "Verstehen: ho, hai und non ho", body: "Ho = ich habe · hai = du hast · non ho = ich habe nicht / ich habe keine. Das h bleibt stumm: ho klingt wie „o“, hai wie „ai“. un fratello ist männlich, una sorella weiblich. Im Plural wird daraus fratelli und sorelle ."),
            ],
            memories: [
                "Merksatz: mio padre / mia madre und questo / questa richten sich nach dem männlichen oder weiblichen Wort. Mit ho sagst du, wen du hast: Ho due fratelli.",
            ],
            dialogue: [
                DialogueLine(id: "5-d1", speaker: "A", italian: "Hai fratelli o sorelle?", german: "Hast du Brüder oder Schwestern?"),
                DialogueLine(id: "5-d2", speaker: "B", italian: "Sì, ho due fratelli.", german: "Ja, ich habe zwei Brüder."),
                DialogueLine(id: "5-d3", speaker: "A", italian: "Come si chiama tuo fratello?", german: "Wie heißt dein Bruder?"),
                DialogueLine(id: "5-d4", speaker: "B", italian: "Si chiama Luca.", german: "Er heißt Luca."),
            ]
        ),
    ]

    static var featuredVocabulary: [VocabularyItem] {
        vocabulary.filter { [.essential, .restaurant, .travel, .smallTalk].contains($0.category) }
    }

    static func makeQuiz(limit: Int = 10, category: VocabularyCategory? = nil) -> [QuizQuestion] {
        let source = category.map { selected in
            vocabulary.filter { $0.category == selected }
        } ?? vocabulary

        let usable = source.filter { !$0.italian.contains(" / ") && $0.german.count < 110 }
        let selected = Array(usable.shuffled().prefix(min(limit, usable.count)))

        return selected.map { item in
            let distractors = Set(vocabulary
                .filter { $0.id != item.id && $0.german != item.german && $0.german.count < 110 }
                .map(\.german))
                .shuffled()
                .prefix(3)

            return QuizQuestion(
                wordID: item.id,
                italian: item.italian,
                pronunciation: item.pronunciation,
                answers: ([item.german] + Array(distractors)).shuffled(),
                correctAnswer: item.german
            )
        }
    }

    static func makeQuiz(wordIDs: Set<Int>, limit: Int = 10) -> [QuizQuestion] {
        let items = vocabulary.filter { wordIDs.contains($0.id) }
        let selected = Array(items.shuffled().prefix(min(limit, items.count)))

        return selected.map { item in
            let distractors = Set(vocabulary
                .filter { $0.id != item.id && $0.german != item.german && $0.german.count < 110 }
                .map(\.german))
                .shuffled()
                .prefix(3)

            return QuizQuestion(
                wordID: item.id,
                italian: item.italian,
                pronunciation: item.pronunciation,
                answers: ([item.german] + Array(distractors)).shuffled(),
                correctAnswer: item.german
            )
        }
    }

    static func groups(from items: [VocabularyItem]) -> [VocabularyGroup] {
        var order: [String] = []
        var grouped: [String: [VocabularyItem]] = [:]

        for item in items {
            if grouped[item.section] == nil { order.append(item.section) }
            grouped[item.section, default: []].append(item)
        }

        return order.map { VocabularyGroup(title: $0, items: grouped[$0] ?? []) }
    }
}
